CREATE DATABASE IF NOT EXISTS curso;

USE curso;

CREATE TABLE IF NOT EXISTS t_usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL
);

CREATE USER IF NOT EXISTS 'curso'@'%' IDENTIFIED BY 'curso';
GRANT ALL PRIVILEGES ON curso.* TO 'curso'@'%';
FLUSH PRIVILEGES;
